name: Build Template

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      build-tool:
        required: true
        type: string
      service-name:
        required: true
        type: string
      project-path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Build
        working-directory: ${{ inputs.project-path }}
        run: |
          if [ "${{ inputs.build-tool }}" = "maven" ]; then
            mvn clean package -DskipTests
          else
            chmod +x gradlew
            ./gradlew clean build -x test
          fi
